deepseek-chat:
  api_key: sk-77393f428fd9428ba91b435497885c11
  base_url: https://api.deepseek.com
  max_tokens: 200
  temperature: 0.1

qwen2-7b-instruct:
  api_key: sk-290ddbae9c8f41d18efdd8355a397076
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  max_tokens: 4000
  temperature: 0.1

llm_cloud_server:
  - deepseek-chat
  - qwen2-7b-instruct
